### ISSUE TITLE
Once borderless, apps are not shown in the list

### ISSUE THREAD

**Issue by woctezuma** [20k/game_window_manager#2]
When I launch the program, I get this screenshot:

![at start](https://i.imgur.com/YiUkfuR.png)

However, if I decide to make Firefox "borderless", then Firefox disappears from the list. "Refresh" does not make it appear. So there is no way to cancel/switch back from borderless to windowed or fullscreen mode.

**Comment by 20k** [comment]
Ah right, I intentionally made that happen to eliminate a bunch of programs from the list. What I might do is have a tickbox which says "only show windowed applications", which you can disable if you want the full list of processes

**Comment by 20k** [comment]
Fixed in v0.12

**Comment by 20k** [comment]
Additionally, applications that you make a profile for are always listed under the next version
