### ISSUE TITLE
What does "make borderless auto" do?

### ISSUE THREAD

**Issue by addrum** [20k/game_window_manager#3]
It seems to work the same as the set to top left option but considering it says "auto" I thought it would "save this so when I next load the app it makes it borderless automatically. If that's what it's meant to do, it doesn't seem to do it for the original Dead Space steam edition. I'm yet to test this on other windows yet.

**Comment by 20k** [comment]
The idea behind this option is that for full screen sized applications, it will make them borderless and set them to the top left. For non full screen sized applications, it will simply set them borderless

It will likely be made obsolete and removed when per-app profiles arrive shortly, at which point I will close this ticket :)

**Comment by 20k** [comment]
Per-application profiles have been added (if slightly clunky for the moment) and make borderless auto has been removed, therefore I am closing this ticket :)
