### ISSUE TITLE
Build fails to missing dep vec\vec.hpp

### ISSUE THREAD

**Issue by Stateford** [20k/game_window_manager#6]
```cpp
1>------ Build started: Project: game_window_manager, Configuration: Debug Win32 ------
1>serialise.cpp
1>d:\cpp\game_window_manager\deps\funserialisation\serialise.hpp(21): fatal error C1083: Cannot open include file: 'vec/vec.hpp': No such file or directory
1>imgui-SFML.cpp
1>imgui.cpp
1>imgui_draw.cpp
1>imgui_freetype.cpp
1>d:\cpp\game_window_manager\deps\imgui\misc\freetype\imgui_freetype.cpp(246): fatal error C1083: Cannot open include file: 'stb_rect_pack.h': No such file or directory
1>main.cpp
1>d:\cpp\game_window_manager\deps\funserialisation\serialise.hpp(21): fatal error C1083: Cannot open include file: 'vec/vec.hpp': No such file or directory
1>Generating Code...
1>Done building project "game_window_manager.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by 20k** [comment]
Just to clarify, you're trying to compile this under a different compiler not using the default build system?

Try defining:

NO_VEC_SUPPORT
NO_COMPRESSION
NET_CLIENT
NO_SFML

I will leave this issue open until I provide a default makefile. Codeblocks files, .cbp, are a very simple human readable format, which might provide further hints if you get stuck, or ask here

**Comment by 20k** [comment]
The project now includes autogenerated makesfiles, however as it assumes GCC they will look for GCC. You might be able to override CC etc to provide MSVC, or configure MSVC in some way to work correctly with them. However I am not totally familiar with makefiles, so if this doesn't work on your end or ends up being too complex I'll look into generating makefiles that assume msvc

**Comment by Stateford** [comment]
Thanks, I got it working on visual studio.

I've never used codeblocks so I was unsure, but it makes sense now, thanks!

**Comment by 20k** [comment]
No problem, glad I could help! I should note that the project structure underwent a revamp extremely recently to split it up into header/cpp files. Its likely it wont change much into the future so I'd recommend resyncing in case you haven't spotted this change :) good luck!
